(function(){
  const D=window.SITE_DATA;
  const themes=[
    {id:'poster',name:'Iranian Poster',fa:'پوستر سینمای ایران',note:'Painted drama, torn paper and cinema marquees.'},
    {id:'carpet',name:'Persian Carpet',fa:'فرش ایرانی',note:'A woven gallery with medallion-shaped frames.'},
    {id:'tehran',name:'Tehran Architecture',fa:'معماری تهران',note:'Qajar arches meet the contemporary city.'},
    {id:'negative',name:'Negative & Polaroid',fa:'نگاتیو و پولاروید',note:'A tactile darkroom and contact-sheet archive.'},
    {id:'press',name:'Press Archive',fa:'روزنامه و مجله',note:'The city arranged as a cultural newspaper.'},
    {id:'theatre',name:'Theatre & Tilework',fa:'تئاتر و کاشی‌کاری',note:'Red velvet, gold leaf and Persian tilework.'}
  ];
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const img=p=>p?'assets/'+p.replace(/^assets\//,''):'assets/theme/'+document.documentElement.dataset.theme+'-panel.png';
  const filmFor=l=>D.films.find(f=>f.id===l.related_film||f.aliases?.includes(l.related_film));
  let currentStory='route',currentLocation=null,audience=1,detailLevel=1;
  function themeCard(t,button=false){return `<${button?'button':'article'} class="theme-tile" data-set-theme="${t.id}"><img src="assets/theme/${t.id}-panel.png" alt="${esc(t.name)} exhibition artwork"><span><b>${esc(t.name)}</b><em dir="rtl">${esc(t.fa)}</em><small>${esc(t.note)}</small></span></${button?'button':'article'}>`}
  function setTheme(id){const t=themes.find(x=>x.id===id)||themes[0];document.documentElement.dataset.theme=t.id;try{localStorage.setItem('tca-static-theme',t.id)}catch(e){}$('#featureImage').src=`assets/theme/${t.id}-panel.png`;$('#featureTitle').textContent=t.name;$('#featureNote').textContent=t.note;$$('[data-set-theme]').forEach(x=>x.classList.toggle('selected',x.dataset.setTheme===id));}
  $('#themeTiles').innerHTML=themes.map(t=>themeCard(t)).join('');$('#themeChoices').innerHTML=themes.map(t=>themeCard(t,true)).join('');
  $$('[data-set-theme]').forEach(x=>x.addEventListener('click',()=>{setTheme(x.dataset.setTheme);if(x.closest('dialog'))$('#themeDialog').close()}));
  $('#themeKey').onclick=()=>$('#themeDialog').showModal();$$('dialog .close').forEach(x=>x.onclick=()=>x.closest('dialog').close());

  function locationCard(l,i){const f=filmFor(l);return `<article class="location-card reveal" data-search="${esc((l.location_name_en+' '+l.location_name_fa+' '+(f?.title_en||'')).toLowerCase())}"><button data-location="${l.id}"><figure><img src="${img(l.film_still_image)}" alt="${esc(l.location_name_en)} film frame" onerror="this.src='assets/theme/${document.documentElement.dataset.theme}-panel.png';this.classList.add('placeholder')"><figcaption>FRAME ${String(i+1).padStart(2,'0')}</figcaption></figure><div><p>${esc(f?.title_en||'Iranian cinema')} · ${f?.year||''}</p><h3>${esc(l.location_name_en)}</h3><b dir="rtl">${esc(l.location_name_fa)}</b><span>${esc(l.neighborhood_or_area||l.city)} →</span></div></button></article>`}
  $('#locationGrid').innerHTML=D.locations.map(locationCard).join('');
  $('#filmRow').innerHTML=D.films.map((f,i)=>`<article class="film-card"><img src="${img(f.poster_image)}" alt="${esc(f.title_en)} poster" onerror="this.src='assets/theme/${document.documentElement.dataset.theme}-panel.png'"><span>0${i+1}</span><div><small>${f.year} · ${esc(f.director)}</small><h3>${esc(f.title_en)}</h3><b dir="rtl">${esc(f.title_fa)}</b><p>${esc(f.short_description)}</p></div></article>`).join('');
  $('#search').oninput=e=>{$$('.location-card').forEach(c=>c.hidden=!c.dataset.search.includes(e.target.value.toLowerCase()))};
  function contextStrings(l){return Object.values(l.geographical_context||{}).filter(x=>typeof x==='string')}
  function adaptiveText(l,a,d){
    const facts=l.facts_trivia||[],evidence=l.evidence||[],context=contextStrings(l);
    const angle={route:'In the one-day itinerary, this stop connects the previous part of Tehran with the next district.',timeline:`In the historical timeline, this location is read through ${filmFor(l)?.year||'its production period'} and its image of Tehran.`,lens:`In the thematic narrative, this ${l.place_type.toLowerCase()} shows how architecture carries social meaning.`}[currentStory];
    const opening=[`This is a real place in Tehran that appears in a film. ${l.scene_description}`,`${angle} ${l.scene_description}`,`Read as a cinematic and urban document, ${angle} ${l.scene_description}`][a];
    const middle=a===0?facts.map(x=>x.replace(/\barchitectural\b/gi,'building').replace(/\burban\b/gi,'city')):a===1?facts:[...facts,...evidence.map(x=>'Evidence: '+x)];
    const long=a===2?[...context,...middle,`Identification status: ${l.match_level||'under review'}. ${l.identification_reason||''}`]:[...middle,...context];
    if(d===0)return opening;
    if(d===1)return [opening,...middle.slice(0,a===2?4:3)].join(' ');
    return [opening,...long].join(' ');
  }
  function renderAdaptive(){
    const l=currentLocation;if(!l)return;
    $('#adaptiveText').textContent=adaptiveText(l,audience,detailLevel);
    $$('.audience-controls button').forEach((b,i)=>b.classList.toggle('active',i===audience));
    $$('.length-controls button').forEach((b,i)=>b.classList.toggle('active',i===detailLevel));
    $('#readingStatus').textContent=`${['Young / introductory','General adult / average','Scholar / advanced'][audience]} · ${['Brief','Medium','Long'][detailLevel]}`;
  }
  function openLocation(id){
    const l=D.locations.find(x=>x.id===id),f=filmFor(l),order=orders[currentStory],at=order.indexOf(l),prev=order[(at-1+order.length)%order.length],next=order[(at+1)%order.length];currentLocation=l;
    $('#detailContent').innerHTML=`<header class="record-header"><p class="eyebrow">${esc(f?.title_en)} · ${f?.year||''} · ${esc(storyCopy[currentStory].label)}</p><h2>${esc(l.location_name_en)}</h2><b dir="rtl">${esc(l.location_name_fa)}</b><span class="record-count">${String(at+1).padStart(2,'0')} / ${String(order.length).padStart(2,'0')}</span></header><div class="compare"><img src="${img(l.current_location_image)}" alt="Location today"><div class="old"><img src="${img(l.film_still_image)}" alt="Film frame"></div><input type="range" min="2" max="98" value="50" aria-label="Compare then and now"><span>THEN · FILM</span><span>NOW · TEHRAN</span></div><div class="reading-console"><div><span>AUDIENCE / COMPETENCE</span><div class="audience-controls"><button>Young</button><button>General</button><button>Scholar</button></div></div><div><span>LEVEL OF DETAIL</span><div class="length-controls"><button>Brief</button><button>Medium</button><button>Long</button></div></div><strong id="readingStatus"></strong></div><div class="detail-text"><section><p class="eyebrow">THE SCENE AND CITY</p><p id="adaptiveText"></p><div class="mode-panels"><details><summary>Do you want to play?</summary><div><h3>Frame finder</h3><p>At the location, identify one architectural anchor visible in both images. Match the camera height and direction, then make your own present-day photograph.</p></div></details><details><summary>Additional details and references</summary><div><h3>Evidence</h3><ol>${(l.evidence||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h3>Sources</h3><ul>${(l.sources||[]).map(x=>`<li><a href="${esc(x)}" target="_blank" rel="noreferrer">${esc(x)}</a></li>`).join('')}</ul></div></details></div></section><aside class="metadata"><h3>Metadata</h3><dl><dt>Type</dt><dd>${esc(l.place_type)}</dd><dt>Area</dt><dd>${esc(l.neighborhood_or_area)}</dd><dt>Address</dt><dd>${esc(l.current_address_or_area)}</dd><dt>Access</dt><dd>${esc(l.visitor_access)}</dd><dt>Location reality</dt><dd>${esc(l.location_reality)}</dd><dt>Identification</dt><dd>${esc(l.match_level)}</dd><dt>Coordinates</dt><dd>${l.coordinates.latitude}, ${l.coordinates.longitude}</dd><dt>Camera orientation</dt><dd>Requires field verification</dd></dl><a href="${esc(l.map_link)}" target="_blank" rel="noreferrer">OPEN DIRECTIONS ↗</a></aside></div><nav class="record-nav"><button data-prev="${prev.id}">← <span><small>Previous in ${esc(storyCopy[currentStory].label)}</small>${esc(prev.location_name_en)}</span></button><button data-next="${next.id}"><span><small>Next in ${esc(storyCopy[currentStory].label)}</small>${esc(next.location_name_en)}</span> →</button></nav>`;
    const range=$('#detailContent .compare input'),old=$('#detailContent .old');range.oninput=()=>old.style.width=range.value+'%';
    $$('.audience-controls button').forEach((b,i)=>b.onclick=()=>{audience=i;renderAdaptive()});$$('.length-controls button').forEach((b,i)=>b.onclick=()=>{detailLevel=i;renderAdaptive()});
    $('#detailContent [data-prev]').onclick=e=>openLocation(e.currentTarget.dataset.prev);$('#detailContent [data-next]').onclick=e=>openLocation(e.currentTarget.dataset.next);renderAdaptive();if(!$('#detailDialog').open)$('#detailDialog').showModal();
  }
  $$('[data-location]').forEach(x=>x.onclick=()=>openLocation(x.dataset.location));
  const orders={route:[...D.locations].sort((a,b)=>b.coordinates.latitude-a.coordinates.latitude),timeline:[...D.locations].sort((a,b)=>(filmFor(a)?.year||0)-(filmFor(b)?.year||0)),lens:[...D.locations].sort((a,b)=>a.place_type.localeCompare(b.place_type))};
  const storyCopy={route:{label:'One-day route',intro:'A plausible single-day journey from the northern garden mansions to the historic and civic centre.',chapter:'Chapter 1 — From private memory to public city',transition:'Begin among northern garden houses, then descend toward Tehran’s cultural and political centre.'},timeline:{label:'Historical timeline',intro:'The required historical narrative orders the locations by the release year of their anchor films.',chapter:'Chapter 1 — Tehran across screen time',transition:'Move from historical and period visions of the capital toward contemporary student life and urban tension.'},lens:{label:'City lenses',intro:'A thematic narrative groups locations by architectural and social function.',chapter:'Chapter 1 — Architecture performs meaning',transition:'Compare palaces, private houses, cultural buildings and civic spaces as active storytelling devices.'}};
  function route(key){currentStory=key;const c=storyCopy[key];$('#storyIntro').textContent=c.intro;$('#chapterTitle').textContent=c.chapter;$('#chapterText').textContent=c.transition;$('#routeStrip').innerHTML=orders[key].map((l,i)=>`<button data-location="${l.id}"><span>${String(i+1).padStart(2,'0')}</span><img src="${img(l.current_location_image)}" alt=""><b>${esc(l.location_name_en)}</b></button>`).join('');$$('#routeStrip [data-location]').forEach(x=>x.onclick=()=>openLocation(x.dataset.location))}
  $$('.story-buttons button').forEach(x=>x.onclick=()=>{$$('.story-buttons button').forEach(b=>b.classList.remove('active'));x.classList.add('active');route(x.dataset.story)});route('route');
  function renderMap(){const ps=D.locations,minLat=Math.min(...ps.map(x=>x.coordinates.latitude)),maxLat=Math.max(...ps.map(x=>x.coordinates.latitude)),minLng=Math.min(...ps.map(x=>x.coordinates.longitude)),maxLng=Math.max(...ps.map(x=>x.coordinates.longitude));$('#mapStage').insertAdjacentHTML('beforeend',ps.map((l,i)=>{const x=7+(l.coordinates.longitude-minLng)/(maxLng-minLng||1)*86,y=7+(1-(l.coordinates.latitude-minLat)/(maxLat-minLat||1))*86;return `<button class="map-point" data-location="${l.id}" style="left:${x}%;top:${y}%" title="${esc(l.location_name_en)}"><span>${i+1}</span><b>${esc(l.location_name_en)}</b></button>`}).join(''));$$('#mapStage [data-location]').forEach(x=>x.onclick=()=>openLocation(x.dataset.location))}renderMap();
  const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});$$('.reveal').forEach(x=>observer.observe(x));
  let savedTheme='poster';try{savedTheme=localStorage.getItem('tca-static-theme')||'poster'}catch(e){}setTheme(savedTheme);
})();
